// Mocks generated by Mockito 5.4.6 from annotations
// in test3/test/features/home/teams_page_patrol_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i15;

import 'package:flutter/material.dart' as _i7;
import 'package:get/get.dart' as _i6;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:test3/features/auth/domain/entities/approved.dart' as _i19;
import 'package:test3/features/auth/domain/entities/enum.dart' as _i20;
import 'package:test3/features/auth/domain/entities/login.dart' as _i18;
import 'package:test3/features/auth/domain/entities/user.dart' as _i17;
import 'package:test3/features/auth/presentation/controller/auth_controller.dart'
    as _i16;
import 'package:test3/features/home/domain/entities/team_entity.dart' as _i9;
import 'package:test3/features/home/domain/entities/user_detail_entity.dart'
    as _i11;
import 'package:test3/features/home/domain/entities/users_entity.dart' as _i10;
import 'package:test3/features/home/domain/usecase/assign_role_usecase.dart'
    as _i4;
import 'package:test3/features/home/domain/usecase/team_usecase.dart' as _i5;
import 'package:test3/features/home/domain/usecase/user_detail_ussecase.dart'
    as _i3;
import 'package:test3/features/home/domain/usecase/users_usecase.dart' as _i2;
import 'package:test3/features/home/presentation/controller/create_team_controller.dart'
    as _i21;
import 'package:test3/features/home/presentation/controller/home_controller.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetAllUsersUseCase_0 extends _i1.SmartFake
    implements _i2.GetAllUsersUseCase {
  _FakeGetAllUsersUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserDetailUseCase_1 extends _i1.SmartFake
    implements _i3.GetUserDetailUseCase {
  _FakeGetUserDetailUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAssignRoleUseCase_2 extends _i1.SmartFake
    implements _i4.AssignRoleUseCase {
  _FakeAssignRoleUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllTeamsUseCase_3 extends _i1.SmartFake
    implements _i5.GetAllTeamsUseCase {
  _FakeGetAllTeamsUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_4<T> extends _i1.SmartFake implements _i6.Rx<T> {
  _FakeRx_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_5 extends _i1.SmartFake implements _i6.RxBool {
  _FakeRxBool_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxString_6 extends _i1.SmartFake implements _i6.RxString {
  _FakeRxString_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_7<E> extends _i1.SmartFake implements _i6.RxList<E> {
  _FakeRxList_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxn_8<T> extends _i1.SmartFake implements _i6.Rxn<T> {
  _FakeRxn_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxInt_9 extends _i1.SmartFake implements _i6.RxInt {
  _FakeRxInt_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_10<T> extends _i1.SmartFake
    implements _i6.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingController_11 extends _i1.SmartFake
    implements _i7.TextEditingController {
  _FakeTextEditingController_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeController extends _i1.Mock implements _i8.HomeController {
  MockHomeController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAllUsersUseCase get getAllUsersUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getAllUsersUseCase),
            returnValue: _FakeGetAllUsersUseCase_0(
              this,
              Invocation.getter(#getAllUsersUseCase),
            ),
          )
          as _i2.GetAllUsersUseCase);

  @override
  _i3.GetUserDetailUseCase get getUserDetailUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getUserDetailUseCase),
            returnValue: _FakeGetUserDetailUseCase_1(
              this,
              Invocation.getter(#getUserDetailUseCase),
            ),
          )
          as _i3.GetUserDetailUseCase);

  @override
  _i4.AssignRoleUseCase get assignRoleUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#assignRoleUseCase),
            returnValue: _FakeAssignRoleUseCase_2(
              this,
              Invocation.getter(#assignRoleUseCase),
            ),
          )
          as _i4.AssignRoleUseCase);

  @override
  _i5.GetAllTeamsUseCase get getAllTeamsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getAllTeamsUseCase),
            returnValue: _FakeGetAllTeamsUseCase_3(
              this,
              Invocation.getter(#getAllTeamsUseCase),
            ),
          )
          as _i5.GetAllTeamsUseCase);

  @override
  _i6.Rx<_i9.TeamEntity?> get currentTeam =>
      (super.noSuchMethod(
            Invocation.getter(#currentTeam),
            returnValue: _FakeRx_4<_i9.TeamEntity?>(
              this,
              Invocation.getter(#currentTeam),
            ),
          )
          as _i6.Rx<_i9.TeamEntity?>);

  @override
  _i6.RxBool get isLoadingGetTeamById =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingGetTeamById),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isLoadingGetTeamById),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxString get errorMessageGetTeamById =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessageGetTeamById),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#errorMessageGetTeamById),
            ),
          )
          as _i6.RxString);

  @override
  _i6.RxBool get isNotificationSelected =>
      (super.noSuchMethod(
            Invocation.getter(#isNotificationSelected),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isNotificationSelected),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get isProfileSelected =>
      (super.noSuchMethod(
            Invocation.getter(#isProfileSelected),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isProfileSelected),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get isLoadingTeam =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingTeam),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#isLoadingTeam)),
          )
          as _i6.RxBool);

  @override
  _i6.RxString get errorMessageTeam =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessageTeam),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#errorMessageTeam),
            ),
          )
          as _i6.RxString);

  @override
  _i6.RxList<_i9.TeamEntity> get teams =>
      (super.noSuchMethod(
            Invocation.getter(#teams),
            returnValue: _FakeRxList_7<_i9.TeamEntity>(
              this,
              Invocation.getter(#teams),
            ),
          )
          as _i6.RxList<_i9.TeamEntity>);

  @override
  _i6.RxList<_i9.TeamEntity> get filteredTeams =>
      (super.noSuchMethod(
            Invocation.getter(#filteredTeams),
            returnValue: _FakeRxList_7<_i9.TeamEntity>(
              this,
              Invocation.getter(#filteredTeams),
            ),
          )
          as _i6.RxList<_i9.TeamEntity>);

  @override
  _i6.RxString get nameFilterTeam =>
      (super.noSuchMethod(
            Invocation.getter(#nameFilterTeam),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#nameFilterTeam),
            ),
          )
          as _i6.RxString);

  @override
  _i6.Rxn<bool> get healthcareFilter =>
      (super.noSuchMethod(
            Invocation.getter(#healthcareFilter),
            returnValue: _FakeRxn_8<bool>(
              this,
              Invocation.getter(#healthcareFilter),
            ),
          )
          as _i6.Rxn<bool>);

  @override
  _i6.Rxn<bool> get householdFilter =>
      (super.noSuchMethod(
            Invocation.getter(#householdFilter),
            returnValue: _FakeRxn_8<bool>(
              this,
              Invocation.getter(#householdFilter),
            ),
          )
          as _i6.Rxn<bool>);

  @override
  _i6.Rxn<bool> get referralFilter =>
      (super.noSuchMethod(
            Invocation.getter(#referralFilter),
            returnValue: _FakeRxn_8<bool>(
              this,
              Invocation.getter(#referralFilter),
            ),
          )
          as _i6.Rxn<bool>);

  @override
  _i6.Rxn<bool> get burialFilter =>
      (super.noSuchMethod(
            Invocation.getter(#burialFilter),
            returnValue: _FakeRxn_8<bool>(
              this,
              Invocation.getter(#burialFilter),
            ),
          )
          as _i6.Rxn<bool>);

  @override
  _i6.RxBool get isFiltersExpandedTeam =>
      (super.noSuchMethod(
            Invocation.getter(#isFiltersExpandedTeam),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isFiltersExpandedTeam),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxInt get currentPageTeam =>
      (super.noSuchMethod(
            Invocation.getter(#currentPageTeam),
            returnValue: _FakeRxInt_9(
              this,
              Invocation.getter(#currentPageTeam),
            ),
          )
          as _i6.RxInt);

  @override
  _i6.RxInt get pageSizeTeam =>
      (super.noSuchMethod(
            Invocation.getter(#pageSizeTeam),
            returnValue: _FakeRxInt_9(this, Invocation.getter(#pageSizeTeam)),
          )
          as _i6.RxInt);

  @override
  _i6.RxBool get hasNextPageTeam =>
      (super.noSuchMethod(
            Invocation.getter(#hasNextPageTeam),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#hasNextPageTeam),
            ),
          )
          as _i6.RxBool);

  @override
  List<_i9.TeamEntity> get healthcareTeams =>
      (super.noSuchMethod(
            Invocation.getter(#healthcareTeams),
            returnValue: <_i9.TeamEntity>[],
          )
          as List<_i9.TeamEntity>);

  @override
  List<_i9.TeamEntity> get householdTeams =>
      (super.noSuchMethod(
            Invocation.getter(#householdTeams),
            returnValue: <_i9.TeamEntity>[],
          )
          as List<_i9.TeamEntity>);

  @override
  List<_i9.TeamEntity> get referralTeams =>
      (super.noSuchMethod(
            Invocation.getter(#referralTeams),
            returnValue: <_i9.TeamEntity>[],
          )
          as List<_i9.TeamEntity>);

  @override
  List<_i9.TeamEntity> get burialTeams =>
      (super.noSuchMethod(
            Invocation.getter(#burialTeams),
            returnValue: <_i9.TeamEntity>[],
          )
          as List<_i9.TeamEntity>);

  @override
  _i6.RxBool get isLoadingUsers =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingUsers),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isLoadingUsers),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxString get errorMessageUsers =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessageUsers),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#errorMessageUsers),
            ),
          )
          as _i6.RxString);

  @override
  _i6.RxList<_i10.UserEntity> get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeRxList_7<_i10.UserEntity>(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i6.RxList<_i10.UserEntity>);

  @override
  _i6.RxBool get isLoadingUserDetail =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingUserDetail),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isLoadingUserDetail),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxString get errorMessageUserDetail =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessageUserDetail),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#errorMessageUserDetail),
            ),
          )
          as _i6.RxString);

  @override
  _i6.Rxn<_i11.UserDetailEntity> get userDetail =>
      (super.noSuchMethod(
            Invocation.getter(#userDetail),
            returnValue: _FakeRxn_8<_i11.UserDetailEntity>(
              this,
              Invocation.getter(#userDetail),
            ),
          )
          as _i6.Rxn<_i11.UserDetailEntity>);

  @override
  _i6.RxBool get isAssigningRole =>
      (super.noSuchMethod(
            Invocation.getter(#isAssigningRole),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isAssigningRole),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxString get selectedRole =>
      (super.noSuchMethod(
            Invocation.getter(#selectedRole),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#selectedRole),
            ),
          )
          as _i6.RxString);

  @override
  List<String> get availableRoles =>
      (super.noSuchMethod(
            Invocation.getter(#availableRoles),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i6.RxString get nameFilter =>
      (super.noSuchMethod(
            Invocation.getter(#nameFilter),
            returnValue: _FakeRxString_6(this, Invocation.getter(#nameFilter)),
          )
          as _i6.RxString);

  @override
  _i6.RxString get emailFilter =>
      (super.noSuchMethod(
            Invocation.getter(#emailFilter),
            returnValue: _FakeRxString_6(this, Invocation.getter(#emailFilter)),
          )
          as _i6.RxString);

  @override
  _i6.RxString get roleFilter =>
      (super.noSuchMethod(
            Invocation.getter(#roleFilter),
            returnValue: _FakeRxString_6(this, Invocation.getter(#roleFilter)),
          )
          as _i6.RxString);

  @override
  _i6.Rxn<bool> get isApprovedFilter =>
      (super.noSuchMethod(
            Invocation.getter(#isApprovedFilter),
            returnValue: _FakeRxn_8<bool>(
              this,
              Invocation.getter(#isApprovedFilter),
            ),
          )
          as _i6.Rxn<bool>);

  @override
  _i6.RxString get sortBy =>
      (super.noSuchMethod(
            Invocation.getter(#sortBy),
            returnValue: _FakeRxString_6(this, Invocation.getter(#sortBy)),
          )
          as _i6.RxString);

  @override
  _i6.RxBool get sortDesc =>
      (super.noSuchMethod(
            Invocation.getter(#sortDesc),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#sortDesc)),
          )
          as _i6.RxBool);

  @override
  _i6.Rxn<DateTime> get registerDateFrom =>
      (super.noSuchMethod(
            Invocation.getter(#registerDateFrom),
            returnValue: _FakeRxn_8<DateTime>(
              this,
              Invocation.getter(#registerDateFrom),
            ),
          )
          as _i6.Rxn<DateTime>);

  @override
  _i6.Rxn<DateTime> get registerDateTo =>
      (super.noSuchMethod(
            Invocation.getter(#registerDateTo),
            returnValue: _FakeRxn_8<DateTime>(
              this,
              Invocation.getter(#registerDateTo),
            ),
          )
          as _i6.Rxn<DateTime>);

  @override
  _i6.RxInt get currentPageUsers =>
      (super.noSuchMethod(
            Invocation.getter(#currentPageUsers),
            returnValue: _FakeRxInt_9(
              this,
              Invocation.getter(#currentPageUsers),
            ),
          )
          as _i6.RxInt);

  @override
  _i6.RxInt get pageSizeUsers =>
      (super.noSuchMethod(
            Invocation.getter(#pageSizeUsers),
            returnValue: _FakeRxInt_9(this, Invocation.getter(#pageSizeUsers)),
          )
          as _i6.RxInt);

  @override
  List<String> get sortOptions =>
      (super.noSuchMethod(
            Invocation.getter(#sortOptions),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get roleOptions =>
      (super.noSuchMethod(
            Invocation.getter(#roleOptions),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i6.RxString get role =>
      (super.noSuchMethod(
            Invocation.getter(#role),
            returnValue: _FakeRxString_6(this, Invocation.getter(#role)),
          )
          as _i6.RxString);

  @override
  _i6.RxString get userName =>
      (super.noSuchMethod(
            Invocation.getter(#userName),
            returnValue: _FakeRxString_6(this, Invocation.getter(#userName)),
          )
          as _i6.RxString);

  @override
  _i6.RxString get userSearchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#userSearchQuery),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#userSearchQuery),
            ),
          )
          as _i6.RxString);

  @override
  List<_i10.UserEntity> get filteredUsers =>
      (super.noSuchMethod(
            Invocation.getter(#filteredUsers),
            returnValue: <_i10.UserEntity>[],
          )
          as List<_i10.UserEntity>);

  @override
  _i6.RxBool get isFiltersExpanded =>
      (super.noSuchMethod(
            Invocation.getter(#isFiltersExpanded),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isFiltersExpanded),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxInt get selectedIndex =>
      (super.noSuchMethod(
            Invocation.getter(#selectedIndex),
            returnValue: _FakeRxInt_9(this, Invocation.getter(#selectedIndex)),
          )
          as _i6.RxInt);

  @override
  _i6.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#isLoading)),
          )
          as _i6.RxBool);

  @override
  _i6.RxString get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as _i6.RxString);

  @override
  _i6.RxBool get isLoadingDetail =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingDetail),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isLoadingDetail),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxString get errorMessageDetail =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessageDetail),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#errorMessageDetail),
            ),
          )
          as _i6.RxString);

  @override
  _i6.Rxn<int> get selectedStatusFilter =>
      (super.noSuchMethod(
            Invocation.getter(#selectedStatusFilter),
            returnValue: _FakeRxn_8<int>(
              this,
              Invocation.getter(#selectedStatusFilter),
            ),
          )
          as _i6.Rxn<int>);

  @override
  _i6.Rxn<int> get selectedTypeFilter =>
      (super.noSuchMethod(
            Invocation.getter(#selectedTypeFilter),
            returnValue: _FakeRxn_8<int>(
              this,
              Invocation.getter(#selectedTypeFilter),
            ),
          )
          as _i6.Rxn<int>);

  @override
  _i6.RxString get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _FakeRxString_6(this, Invocation.getter(#searchQuery)),
          )
          as _i6.RxString);

  @override
  List<Map<String, dynamic>> get statusList =>
      (super.noSuchMethod(
            Invocation.getter(#statusList),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> get alertTypeList =>
      (super.noSuchMethod(
            Invocation.getter(#alertTypeList),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  List<_i10.UserEntity> get approvedUsers =>
      (super.noSuchMethod(
            Invocation.getter(#approvedUsers),
            returnValue: <_i10.UserEntity>[],
          )
          as List<_i10.UserEntity>);

  @override
  List<_i10.UserEntity> get pendingUsers =>
      (super.noSuchMethod(
            Invocation.getter(#pendingUsers),
            returnValue: <_i10.UserEntity>[],
          )
          as List<_i10.UserEntity>);

  @override
  List<_i10.UserEntity> get doctorUsers =>
      (super.noSuchMethod(
            Invocation.getter(#doctorUsers),
            returnValue: <_i10.UserEntity>[],
          )
          as List<_i10.UserEntity>);

  @override
  List<_i10.UserEntity> get adminUsers =>
      (super.noSuchMethod(
            Invocation.getter(#adminUsers),
            returnValue: <_i10.UserEntity>[],
          )
          as List<_i10.UserEntity>);

  @override
  int get totalUsers =>
      (super.noSuchMethod(Invocation.getter(#totalUsers), returnValue: 0)
          as int);

  @override
  int get approvedCount =>
      (super.noSuchMethod(Invocation.getter(#approvedCount), returnValue: 0)
          as int);

  @override
  int get pendingCount =>
      (super.noSuchMethod(Invocation.getter(#pendingCount), returnValue: 0)
          as int);

  @override
  int get totalTeams =>
      (super.noSuchMethod(Invocation.getter(#totalTeams), returnValue: 0)
          as int);

  @override
  int get healthcareTeamsCount =>
      (super.noSuchMethod(
            Invocation.getter(#healthcareTeamsCount),
            returnValue: 0,
          )
          as int);

  @override
  int get householdTeamsCount =>
      (super.noSuchMethod(
            Invocation.getter(#householdTeamsCount),
            returnValue: 0,
          )
          as int);

  @override
  int get referralTeamsCount =>
      (super.noSuchMethod(
            Invocation.getter(#referralTeamsCount),
            returnValue: 0,
          )
          as int);

  @override
  int get burialTeamsCount =>
      (super.noSuchMethod(Invocation.getter(#burialTeamsCount), returnValue: 0)
          as int);

  @override
  int get activeFiltersCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeFiltersCount),
            returnValue: 0,
          )
          as int);

  @override
  set isLoadingTeam(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingTeam, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessageTeam(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#errorMessageTeam, value),
    returnValueForMissingStub: null,
  );

  @override
  set teams(_i6.RxList<_i9.TeamEntity>? value) => super.noSuchMethod(
    Invocation.setter(#teams, value),
    returnValueForMissingStub: null,
  );

  @override
  set filteredTeams(_i6.RxList<_i9.TeamEntity>? value) => super.noSuchMethod(
    Invocation.setter(#filteredTeams, value),
    returnValueForMissingStub: null,
  );

  @override
  set nameFilterTeam(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#nameFilterTeam, value),
    returnValueForMissingStub: null,
  );

  @override
  set healthcareFilter(_i6.Rxn<bool>? value) => super.noSuchMethod(
    Invocation.setter(#healthcareFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set householdFilter(_i6.Rxn<bool>? value) => super.noSuchMethod(
    Invocation.setter(#householdFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set referralFilter(_i6.Rxn<bool>? value) => super.noSuchMethod(
    Invocation.setter(#referralFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set burialFilter(_i6.Rxn<bool>? value) => super.noSuchMethod(
    Invocation.setter(#burialFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set isFiltersExpandedTeam(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isFiltersExpandedTeam, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentPageTeam(_i6.RxInt? value) => super.noSuchMethod(
    Invocation.setter(#currentPageTeam, value),
    returnValueForMissingStub: null,
  );

  @override
  set pageSizeTeam(_i6.RxInt? value) => super.noSuchMethod(
    Invocation.setter(#pageSizeTeam, value),
    returnValueForMissingStub: null,
  );

  @override
  set hasNextPageTeam(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#hasNextPageTeam, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingUsers(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingUsers, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessageUsers(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#errorMessageUsers, value),
    returnValueForMissingStub: null,
  );

  @override
  set users(_i6.RxList<_i10.UserEntity>? value) => super.noSuchMethod(
    Invocation.setter(#users, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingUserDetail(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingUserDetail, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessageUserDetail(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#errorMessageUserDetail, value),
    returnValueForMissingStub: null,
  );

  @override
  set userDetail(_i6.Rxn<_i11.UserDetailEntity>? value) => super.noSuchMethod(
    Invocation.setter(#userDetail, value),
    returnValueForMissingStub: null,
  );

  @override
  set isAssigningRole(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isAssigningRole, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedRole(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#selectedRole, value),
    returnValueForMissingStub: null,
  );

  @override
  set nameFilter(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#nameFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set emailFilter(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#emailFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set roleFilter(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#roleFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set isApprovedFilter(_i6.Rxn<bool>? value) => super.noSuchMethod(
    Invocation.setter(#isApprovedFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set sortBy(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#sortBy, value),
    returnValueForMissingStub: null,
  );

  @override
  set sortDesc(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#sortDesc, value),
    returnValueForMissingStub: null,
  );

  @override
  set registerDateFrom(_i6.Rxn<DateTime>? value) => super.noSuchMethod(
    Invocation.setter(#registerDateFrom, value),
    returnValueForMissingStub: null,
  );

  @override
  set registerDateTo(_i6.Rxn<DateTime>? value) => super.noSuchMethod(
    Invocation.setter(#registerDateTo, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentPageUsers(_i6.RxInt? value) => super.noSuchMethod(
    Invocation.setter(#currentPageUsers, value),
    returnValueForMissingStub: null,
  );

  @override
  set pageSizeUsers(_i6.RxInt? value) => super.noSuchMethod(
    Invocation.setter(#pageSizeUsers, value),
    returnValueForMissingStub: null,
  );

  @override
  set role(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#role, value),
    returnValueForMissingStub: null,
  );

  @override
  set userName(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#userName, value),
    returnValueForMissingStub: null,
  );

  @override
  set userSearchQuery(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#userSearchQuery, value),
    returnValueForMissingStub: null,
  );

  @override
  set isFiltersExpanded(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isFiltersExpanded, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedIndex(_i6.RxInt? value) => super.noSuchMethod(
    Invocation.setter(#selectedIndex, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingDetail(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingDetail, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessageDetail(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#errorMessageDetail, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedStatusFilter(_i6.Rxn<int>? value) => super.noSuchMethod(
    Invocation.setter(#selectedStatusFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedTypeFilter(_i6.Rxn<int>? value) => super.noSuchMethod(
    Invocation.setter(#selectedTypeFilter, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchQuery(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#searchQuery, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_10<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i6.InternalFinalCallback<void>);

  @override
  _i6.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_10<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i6.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void setUserSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setUserSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleFiltersExpansion() => super.noSuchMethod(
    Invocation.method(#toggleFiltersExpansion, []),
    returnValueForMissingStub: null,
  );

  @override
  void closeFilters() => super.noSuchMethod(
    Invocation.method(#closeFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  void openFilters() => super.noSuchMethod(
    Invocation.method(#openFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  void changePage(int? index) => super.noSuchMethod(
    Invocation.method(#changePage, [index]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> fetchUsers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsers, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void setNameFilter(String? name) => super.noSuchMethod(
    Invocation.method(#setNameFilter, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void setEmailFilter(String? email) => super.noSuchMethod(
    Invocation.method(#setEmailFilter, [email]),
    returnValueForMissingStub: null,
  );

  @override
  void setRoleFilter(String? role) => super.noSuchMethod(
    Invocation.method(#setRoleFilter, [role]),
    returnValueForMissingStub: null,
  );

  @override
  void setApprovalFilter(bool? isApproved) => super.noSuchMethod(
    Invocation.method(#setApprovalFilter, [isApproved]),
    returnValueForMissingStub: null,
  );

  @override
  void setSortBy(String? sort) => super.noSuchMethod(
    Invocation.method(#setSortBy, [sort]),
    returnValueForMissingStub: null,
  );

  @override
  void setSortDirection(bool? desc) => super.noSuchMethod(
    Invocation.method(#setSortDirection, [desc]),
    returnValueForMissingStub: null,
  );

  @override
  void setDateRange(DateTime? from, DateTime? to) => super.noSuchMethod(
    Invocation.method(#setDateRange, [from, to]),
    returnValueForMissingStub: null,
  );

  @override
  void resetPagination() => super.noSuchMethod(
    Invocation.method(#resetPagination, []),
    returnValueForMissingStub: null,
  );

  @override
  void nextPage() => super.noSuchMethod(
    Invocation.method(#nextPage, []),
    returnValueForMissingStub: null,
  );

  @override
  void previousPage() => super.noSuchMethod(
    Invocation.method(#previousPage, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToPage(int? page) => super.noSuchMethod(
    Invocation.method(#goToPage, [page]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAllFilters() => super.noSuchMethod(
    Invocation.method(#clearAllFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  void applyFiltersUsers() => super.noSuchMethod(
    Invocation.method(#applyFiltersUsers, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> fetchUserDetail({
    required String? userId,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserDetail, [], {
              #userId: userId,
              #currentUserId: currentUserId,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void clearUserDetail() => super.noSuchMethod(
    Invocation.method(#clearUserDetail, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<bool> assignRoleToUser({
    required String? userId,
    required String? roleName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#assignRoleToUser, [], {
              #userId: userId,
              #roleName: roleName,
            }),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  void setSelectedRole(String? role) => super.noSuchMethod(
    Invocation.method(#setSelectedRole, [role]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelectedRole() => super.noSuchMethod(
    Invocation.method(#clearSelectedRole, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> fetchTeams() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTeams, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void nextPageTeam() => super.noSuchMethod(
    Invocation.method(#nextPageTeam, []),
    returnValueForMissingStub: null,
  );

  @override
  void previousPageTeam() => super.noSuchMethod(
    Invocation.method(#previousPageTeam, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetToFirstPageTeam() => super.noSuchMethod(
    Invocation.method(#resetToFirstPageTeam, []),
    returnValueForMissingStub: null,
  );

  @override
  String getPaginationInfoTeam() =>
      (super.noSuchMethod(
            Invocation.method(#getPaginationInfoTeam, []),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#getPaginationInfoTeam, []),
            ),
          )
          as String);

  @override
  void applyLocalFilters() => super.noSuchMethod(
    Invocation.method(#applyLocalFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  void setNameFilterTeam(String? name) => super.noSuchMethod(
    Invocation.method(#setNameFilterTeam, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void setHealthcareFilter(bool? value) => super.noSuchMethod(
    Invocation.method(#setHealthcareFilter, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setHouseholdFilter(bool? value) => super.noSuchMethod(
    Invocation.method(#setHouseholdFilter, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setReferralFilter(bool? value) => super.noSuchMethod(
    Invocation.method(#setReferralFilter, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setBurialFilter(bool? value) => super.noSuchMethod(
    Invocation.method(#setBurialFilter, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleFiltersExpansionTeam() => super.noSuchMethod(
    Invocation.method(#toggleFiltersExpansionTeam, []),
    returnValueForMissingStub: null,
  );

  @override
  void applyFiltersTeam() => super.noSuchMethod(
    Invocation.method(#applyFiltersTeam, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearAllFiltersTeam() => super.noSuchMethod(
    Invocation.method(#clearAllFiltersTeam, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListener(_i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i14.Disposer);

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i15.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListenerId(Object? key, _i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i14.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i16.AuthController {
  MockAuthController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.RxBool get showHello =>
      (super.noSuchMethod(
            Invocation.getter(#showHello),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#showHello)),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get showWelcome =>
      (super.noSuchMethod(
            Invocation.getter(#showWelcome),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#showWelcome)),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get showSignIn =>
      (super.noSuchMethod(
            Invocation.getter(#showSignIn),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#showSignIn)),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get isLoadingGoogle =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingGoogle),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isLoadingGoogle),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get isLoadingGoogleRegister =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingGoogleRegister),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isLoadingGoogleRegister),
            ),
          )
          as _i6.RxBool);

  @override
  _i7.TextEditingController get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _FakeTextEditingController_11(
              this,
              Invocation.getter(#name),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get lastName =>
      (super.noSuchMethod(
            Invocation.getter(#lastName),
            returnValue: _FakeTextEditingController_11(
              this,
              Invocation.getter(#lastName),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _FakeTextEditingController_11(
              this,
              Invocation.getter(#password),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _FakeTextEditingController_11(
              this,
              Invocation.getter(#email),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i6.RxString get userEmail =>
      (super.noSuchMethod(
            Invocation.getter(#userEmail),
            returnValue: _FakeRxString_6(this, Invocation.getter(#userEmail)),
          )
          as _i6.RxString);

  @override
  _i6.RxString get token =>
      (super.noSuchMethod(
            Invocation.getter(#token),
            returnValue: _FakeRxString_6(this, Invocation.getter(#token)),
          )
          as _i6.RxString);

  @override
  _i6.RxString get fcmToken =>
      (super.noSuchMethod(
            Invocation.getter(#fcmToken),
            returnValue: _FakeRxString_6(this, Invocation.getter(#fcmToken)),
          )
          as _i6.RxString);

  @override
  _i7.TextEditingController get emailLogin =>
      (super.noSuchMethod(
            Invocation.getter(#emailLogin),
            returnValue: _FakeTextEditingController_11(
              this,
              Invocation.getter(#emailLogin),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get passwordLogin =>
      (super.noSuchMethod(
            Invocation.getter(#passwordLogin),
            returnValue: _FakeTextEditingController_11(
              this,
              Invocation.getter(#passwordLogin),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i6.RxBool get isLoadingEnums =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingEnums),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isLoadingEnums),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxString get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as _i6.RxString);

  @override
  _i6.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#isLoading)),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get isLoadingLogin =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingLogin),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isLoadingLogin),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get isLoadingCheckIsApproved =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingCheckIsApproved),
            returnValue: _FakeRxBool_5(
              this,
              Invocation.getter(#isLoadingCheckIsApproved),
            ),
          )
          as _i6.RxBool);

  @override
  _i6.Rxn<_i17.User> get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue: _FakeRxn_8<_i17.User>(
              this,
              Invocation.getter(#currentUser),
            ),
          )
          as _i6.Rxn<_i17.User>);

  @override
  _i6.Rxn<_i18.LoginEntity> get currentLoginUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentLoginUser),
            returnValue: _FakeRxn_8<_i18.LoginEntity>(
              this,
              Invocation.getter(#currentLoginUser),
            ),
          )
          as _i6.Rxn<_i18.LoginEntity>);

  @override
  _i6.Rxn<_i19.ApprovedEntity> get currentUserIsApproved =>
      (super.noSuchMethod(
            Invocation.getter(#currentUserIsApproved),
            returnValue: _FakeRxn_8<_i19.ApprovedEntity>(
              this,
              Invocation.getter(#currentUserIsApproved),
            ),
          )
          as _i6.Rxn<_i19.ApprovedEntity>);

  @override
  _i6.Rxn<_i20.EnumsResponse> get enumsResponse =>
      (super.noSuchMethod(
            Invocation.getter(#enumsResponse),
            returnValue: _FakeRxn_8<_i20.EnumsResponse>(
              this,
              Invocation.getter(#enumsResponse),
            ),
          )
          as _i6.Rxn<_i20.EnumsResponse>);

  @override
  _i6.RxList<_i20.EnumItem> get alertTypes =>
      (super.noSuchMethod(
            Invocation.getter(#alertTypes),
            returnValue: _FakeRxList_7<_i20.EnumItem>(
              this,
              Invocation.getter(#alertTypes),
            ),
          )
          as _i6.RxList<_i20.EnumItem>);

  @override
  _i6.RxInt get selectedAlertIndex =>
      (super.noSuchMethod(
            Invocation.getter(#selectedAlertIndex),
            returnValue: _FakeRxInt_9(
              this,
              Invocation.getter(#selectedAlertIndex),
            ),
          )
          as _i6.RxInt);

  @override
  set showHello(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#showHello, value),
    returnValueForMissingStub: null,
  );

  @override
  set showWelcome(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#showWelcome, value),
    returnValueForMissingStub: null,
  );

  @override
  set showSignIn(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#showSignIn, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingGoogle(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingGoogle, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingGoogleRegister(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingGoogleRegister, value),
    returnValueForMissingStub: null,
  );

  @override
  set userEmail(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#userEmail, value),
    returnValueForMissingStub: null,
  );

  @override
  set token(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#token, value),
    returnValueForMissingStub: null,
  );

  @override
  set userName(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#userName, value),
    returnValueForMissingStub: null,
  );

  @override
  set fcmToken(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#fcmToken, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingEnums(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingEnums, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(_i6.RxString? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingLogin(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingLogin, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingCheckIsApproved(_i6.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingCheckIsApproved, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentUser(_i6.Rxn<_i17.User>? value) => super.noSuchMethod(
    Invocation.setter(#currentUser, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentLoginUser(_i6.Rxn<_i18.LoginEntity>? value) => super.noSuchMethod(
    Invocation.setter(#currentLoginUser, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentUserIsApproved(_i6.Rxn<_i19.ApprovedEntity>? value) =>
      super.noSuchMethod(
        Invocation.setter(#currentUserIsApproved, value),
        returnValueForMissingStub: null,
      );

  @override
  set enumsResponse(_i6.Rxn<_i20.EnumsResponse>? value) => super.noSuchMethod(
    Invocation.setter(#enumsResponse, value),
    returnValueForMissingStub: null,
  );

  @override
  set alertTypes(_i6.RxList<_i20.EnumItem>? value) => super.noSuchMethod(
    Invocation.setter(#alertTypes, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedAlertIndex(_i6.RxInt? value) => super.noSuchMethod(
    Invocation.setter(#selectedAlertIndex, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_10<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i6.InternalFinalCallback<void>);

  @override
  _i6.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_10<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i6.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void changeAlertType(int? index) => super.noSuchMethod(
    Invocation.method(#changeAlertType, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void runAnimations() => super.noSuchMethod(
    Invocation.method(#runAnimations, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> registerUser({
    required String? name,
    required String? lastname,
    required String? phoneNumber,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [], {
              #name: name,
              #lastname: lastname,
              #phoneNumber: phoneNumber,
              #email: email,
              #password: password,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> quickLogout() =>
      (super.noSuchMethod(
            Invocation.method(#quickLogout, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> loginUser({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> checkUserIsApproved({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#checkUserIsApproved, [], {#userId: userId}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> registerWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#registerWithGoogle, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> loadUserFromPrefs() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserFromPrefs, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListener(_i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i14.Disposer);

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i15.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListenerId(Object? key, _i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i14.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CreateTeamController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTeamController extends _i1.Mock
    implements _i21.CreateTeamController {
  MockCreateTeamController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#isLoading)),
          )
          as _i6.RxBool);

  @override
  _i6.RxString get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as _i6.RxString);

  @override
  _i7.TextEditingController get nameController =>
      (super.noSuchMethod(
            Invocation.getter(#nameController),
            returnValue: _FakeTextEditingController_11(
              this,
              Invocation.getter(#nameController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get descriptionController =>
      (super.noSuchMethod(
            Invocation.getter(#descriptionController),
            returnValue: _FakeTextEditingController_11(
              this,
              Invocation.getter(#descriptionController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get searchController =>
      (super.noSuchMethod(
            Invocation.getter(#searchController),
            returnValue: _FakeTextEditingController_11(
              this,
              Invocation.getter(#searchController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i6.RxBool get isHealthcare =>
      (super.noSuchMethod(
            Invocation.getter(#isHealthcare),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#isHealthcare)),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get isHousehold =>
      (super.noSuchMethod(
            Invocation.getter(#isHousehold),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#isHousehold)),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get isReferral =>
      (super.noSuchMethod(
            Invocation.getter(#isReferral),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#isReferral)),
          )
          as _i6.RxBool);

  @override
  _i6.RxBool get isBurial =>
      (super.noSuchMethod(
            Invocation.getter(#isBurial),
            returnValue: _FakeRxBool_5(this, Invocation.getter(#isBurial)),
          )
          as _i6.RxBool);

  @override
  _i6.RxList<String> get selectedMembers =>
      (super.noSuchMethod(
            Invocation.getter(#selectedMembers),
            returnValue: _FakeRxList_7<String>(
              this,
              Invocation.getter(#selectedMembers),
            ),
          )
          as _i6.RxList<String>);

  @override
  _i6.RxString get selectedRepresentative =>
      (super.noSuchMethod(
            Invocation.getter(#selectedRepresentative),
            returnValue: _FakeRxString_6(
              this,
              Invocation.getter(#selectedRepresentative),
            ),
          )
          as _i6.RxString);

  @override
  _i6.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_10<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i6.InternalFinalCallback<void>);

  @override
  _i6.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_10<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i6.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void setRepresentative(String? userId) => super.noSuchMethod(
    Invocation.method(#setRepresentative, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> createTeamWithMembers() =>
      (super.noSuchMethod(
            Invocation.method(#createTeamWithMembers, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void toggleMemberSelection(String? userId) => super.noSuchMethod(
    Invocation.method(#toggleMemberSelection, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListener(_i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i14.Disposer);

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i15.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListenerId(Object? key, _i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i14.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
