// Mocks generated by Mockito 5.4.6 from annotations
// in test3/test/features/profile/profile_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:io' as _i10;
import 'dart:ui' as _i13;

import 'package:flutter/material.dart' as _i6;
import 'package:get/get.dart' as _i5;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test3/core/theme/theme_controller.dart' as _i19;
import 'package:test3/features/auth/domain/entities/approved.dart' as _i17;
import 'package:test3/features/auth/domain/entities/enum.dart' as _i18;
import 'package:test3/features/auth/domain/entities/login.dart' as _i16;
import 'package:test3/features/auth/domain/entities/user.dart' as _i15;
import 'package:test3/features/auth/presentation/controller/auth_controller.dart'
    as _i14;
import 'package:test3/features/profile/domain/entities/info_user.dart' as _i8;
import 'package:test3/features/profile/domain/entities/update_user.dart' as _i9;
import 'package:test3/features/profile/domain/usecase/chnage_password_usecase.dart'
    as _i4;
import 'package:test3/features/profile/domain/usecase/get_user_info_usecase.dart'
    as _i2;
import 'package:test3/features/profile/domain/usecase/update_user_profile_usecase.dart'
    as _i3;
import 'package:test3/features/profile/presentation/controller/profile_controller.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetUserProfile_0 extends _i1.SmartFake
    implements _i2.GetUserProfile {
  _FakeGetUserProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateUserProfile_1 extends _i1.SmartFake
    implements _i3.UpdateUserProfile {
  _FakeUpdateUserProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordUseCase_2 extends _i1.SmartFake
    implements _i4.ChangePasswordUseCase {
  _FakeChangePasswordUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxn_3<T> extends _i1.SmartFake implements _i5.Rxn<T> {
  _FakeRxn_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_4 extends _i1.SmartFake implements _i5.RxBool {
  _FakeRxBool_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingController_5 extends _i1.SmartFake
    implements _i6.TextEditingController {
  _FakeTextEditingController_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_6<T> extends _i1.SmartFake implements _i5.Rx<T> {
  _FakeRx_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_7<T> extends _i1.SmartFake
    implements _i5.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxString_8 extends _i1.SmartFake implements _i5.RxString {
  _FakeRxString_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_9<E> extends _i1.SmartFake implements _i5.RxList<E> {
  _FakeRxList_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxInt_10 extends _i1.SmartFake implements _i5.RxInt {
  _FakeRxInt_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileController].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileController extends _i1.Mock implements _i7.ProfileController {
  MockProfileController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetUserProfile get getUserProfile =>
      (super.noSuchMethod(
            Invocation.getter(#getUserProfile),
            returnValue: _FakeGetUserProfile_0(
              this,
              Invocation.getter(#getUserProfile),
            ),
          )
          as _i2.GetUserProfile);

  @override
  _i3.UpdateUserProfile get updateUserProfile =>
      (super.noSuchMethod(
            Invocation.getter(#updateUserProfile),
            returnValue: _FakeUpdateUserProfile_1(
              this,
              Invocation.getter(#updateUserProfile),
            ),
          )
          as _i3.UpdateUserProfile);

  @override
  _i4.ChangePasswordUseCase get changePasswordUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#changePasswordUseCase),
            returnValue: _FakeChangePasswordUseCase_2(
              this,
              Invocation.getter(#changePasswordUseCase),
            ),
          )
          as _i4.ChangePasswordUseCase);

  @override
  _i5.Rxn<_i8.UserInfo> get userInfo =>
      (super.noSuchMethod(
            Invocation.getter(#userInfo),
            returnValue: _FakeRxn_3<_i8.UserInfo>(
              this,
              Invocation.getter(#userInfo),
            ),
          )
          as _i5.Rxn<_i8.UserInfo>);

  @override
  _i5.Rxn<_i9.UserUpdate> get userUpdateInfo =>
      (super.noSuchMethod(
            Invocation.getter(#userUpdateInfo),
            returnValue: _FakeRxn_3<_i9.UserUpdate>(
              this,
              Invocation.getter(#userUpdateInfo),
            ),
          )
          as _i5.Rxn<_i9.UserUpdate>);

  @override
  _i5.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_4(this, Invocation.getter(#isLoading)),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get isLoadingUpdate =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingUpdate),
            returnValue: _FakeRxBool_4(
              this,
              Invocation.getter(#isLoadingUpdate),
            ),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get isLoadingChangePassword =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingChangePassword),
            returnValue: _FakeRxBool_4(
              this,
              Invocation.getter(#isLoadingChangePassword),
            ),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get showHello =>
      (super.noSuchMethod(
            Invocation.getter(#showHello),
            returnValue: _FakeRxBool_4(this, Invocation.getter(#showHello)),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get showWelcome =>
      (super.noSuchMethod(
            Invocation.getter(#showWelcome),
            returnValue: _FakeRxBool_4(this, Invocation.getter(#showWelcome)),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get showSignIn =>
      (super.noSuchMethod(
            Invocation.getter(#showSignIn),
            returnValue: _FakeRxBool_4(this, Invocation.getter(#showSignIn)),
          )
          as _i5.RxBool);

  @override
  _i6.TextEditingController get currentPassword =>
      (super.noSuchMethod(
            Invocation.getter(#currentPassword),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#currentPassword),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get newPassword =>
      (super.noSuchMethod(
            Invocation.getter(#newPassword),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#newPassword),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#name),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get lastName =>
      (super.noSuchMethod(
            Invocation.getter(#lastName),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#lastName),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i5.Rx<_i10.File?> get imageFile =>
      (super.noSuchMethod(
            Invocation.getter(#imageFile),
            returnValue: _FakeRx_6<_i10.File?>(
              this,
              Invocation.getter(#imageFile),
            ),
          )
          as _i5.Rx<_i10.File?>);

  @override
  set userInfo(_i5.Rxn<_i8.UserInfo>? value) => super.noSuchMethod(
    Invocation.setter(#userInfo, value),
    returnValueForMissingStub: null,
  );

  @override
  set userUpdateInfo(_i5.Rxn<_i9.UserUpdate>? value) => super.noSuchMethod(
    Invocation.setter(#userUpdateInfo, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingUpdate(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingUpdate, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingChangePassword(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingChangePassword, value),
    returnValueForMissingStub: null,
  );

  @override
  set showHello(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#showHello, value),
    returnValueForMissingStub: null,
  );

  @override
  set showWelcome(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#showWelcome, value),
    returnValueForMissingStub: null,
  );

  @override
  set showSignIn(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#showSignIn, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_7<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i5.InternalFinalCallback<void>);

  @override
  _i5.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_7<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i5.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> pickImage() =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> fetchUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> updateProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [userId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> changePassword(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [userId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListener(_i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i13.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListenerId(Object? key, _i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i14.AuthController {
  MockAuthController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.RxBool get showHello =>
      (super.noSuchMethod(
            Invocation.getter(#showHello),
            returnValue: _FakeRxBool_4(this, Invocation.getter(#showHello)),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get showWelcome =>
      (super.noSuchMethod(
            Invocation.getter(#showWelcome),
            returnValue: _FakeRxBool_4(this, Invocation.getter(#showWelcome)),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get showSignIn =>
      (super.noSuchMethod(
            Invocation.getter(#showSignIn),
            returnValue: _FakeRxBool_4(this, Invocation.getter(#showSignIn)),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get isLoadingGoogle =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingGoogle),
            returnValue: _FakeRxBool_4(
              this,
              Invocation.getter(#isLoadingGoogle),
            ),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get isLoadingGoogleRegister =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingGoogleRegister),
            returnValue: _FakeRxBool_4(
              this,
              Invocation.getter(#isLoadingGoogleRegister),
            ),
          )
          as _i5.RxBool);

  @override
  _i6.TextEditingController get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#name),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get lastName =>
      (super.noSuchMethod(
            Invocation.getter(#lastName),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#lastName),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#password),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#email),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i5.RxString get userEmail =>
      (super.noSuchMethod(
            Invocation.getter(#userEmail),
            returnValue: _FakeRxString_8(this, Invocation.getter(#userEmail)),
          )
          as _i5.RxString);

  @override
  _i5.RxString get token =>
      (super.noSuchMethod(
            Invocation.getter(#token),
            returnValue: _FakeRxString_8(this, Invocation.getter(#token)),
          )
          as _i5.RxString);

  @override
  _i5.RxString get fcmToken =>
      (super.noSuchMethod(
            Invocation.getter(#fcmToken),
            returnValue: _FakeRxString_8(this, Invocation.getter(#fcmToken)),
          )
          as _i5.RxString);

  @override
  _i6.TextEditingController get emailLogin =>
      (super.noSuchMethod(
            Invocation.getter(#emailLogin),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#emailLogin),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get passwordLogin =>
      (super.noSuchMethod(
            Invocation.getter(#passwordLogin),
            returnValue: _FakeTextEditingController_5(
              this,
              Invocation.getter(#passwordLogin),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i5.RxBool get isLoadingEnums =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingEnums),
            returnValue: _FakeRxBool_4(
              this,
              Invocation.getter(#isLoadingEnums),
            ),
          )
          as _i5.RxBool);

  @override
  _i5.RxString get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _FakeRxString_8(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as _i5.RxString);

  @override
  _i5.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_4(this, Invocation.getter(#isLoading)),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get isLoadingLogin =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingLogin),
            returnValue: _FakeRxBool_4(
              this,
              Invocation.getter(#isLoadingLogin),
            ),
          )
          as _i5.RxBool);

  @override
  _i5.RxBool get isLoadingCheckIsApproved =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingCheckIsApproved),
            returnValue: _FakeRxBool_4(
              this,
              Invocation.getter(#isLoadingCheckIsApproved),
            ),
          )
          as _i5.RxBool);

  @override
  _i5.Rxn<_i15.User> get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue: _FakeRxn_3<_i15.User>(
              this,
              Invocation.getter(#currentUser),
            ),
          )
          as _i5.Rxn<_i15.User>);

  @override
  _i5.Rxn<_i16.LoginEntity> get currentLoginUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentLoginUser),
            returnValue: _FakeRxn_3<_i16.LoginEntity>(
              this,
              Invocation.getter(#currentLoginUser),
            ),
          )
          as _i5.Rxn<_i16.LoginEntity>);

  @override
  _i5.Rxn<_i17.ApprovedEntity> get currentUserIsApproved =>
      (super.noSuchMethod(
            Invocation.getter(#currentUserIsApproved),
            returnValue: _FakeRxn_3<_i17.ApprovedEntity>(
              this,
              Invocation.getter(#currentUserIsApproved),
            ),
          )
          as _i5.Rxn<_i17.ApprovedEntity>);

  @override
  _i5.Rxn<_i18.EnumsResponse> get enumsResponse =>
      (super.noSuchMethod(
            Invocation.getter(#enumsResponse),
            returnValue: _FakeRxn_3<_i18.EnumsResponse>(
              this,
              Invocation.getter(#enumsResponse),
            ),
          )
          as _i5.Rxn<_i18.EnumsResponse>);

  @override
  _i5.RxList<_i18.EnumItem> get alertTypes =>
      (super.noSuchMethod(
            Invocation.getter(#alertTypes),
            returnValue: _FakeRxList_9<_i18.EnumItem>(
              this,
              Invocation.getter(#alertTypes),
            ),
          )
          as _i5.RxList<_i18.EnumItem>);

  @override
  _i5.RxInt get selectedAlertIndex =>
      (super.noSuchMethod(
            Invocation.getter(#selectedAlertIndex),
            returnValue: _FakeRxInt_10(
              this,
              Invocation.getter(#selectedAlertIndex),
            ),
          )
          as _i5.RxInt);

  @override
  set showHello(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#showHello, value),
    returnValueForMissingStub: null,
  );

  @override
  set showWelcome(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#showWelcome, value),
    returnValueForMissingStub: null,
  );

  @override
  set showSignIn(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#showSignIn, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingGoogle(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingGoogle, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingGoogleRegister(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingGoogleRegister, value),
    returnValueForMissingStub: null,
  );

  @override
  set userEmail(_i5.RxString? value) => super.noSuchMethod(
    Invocation.setter(#userEmail, value),
    returnValueForMissingStub: null,
  );

  @override
  set token(_i5.RxString? value) => super.noSuchMethod(
    Invocation.setter(#token, value),
    returnValueForMissingStub: null,
  );

  @override
  set userName(_i5.RxString? value) => super.noSuchMethod(
    Invocation.setter(#userName, value),
    returnValueForMissingStub: null,
  );

  @override
  set fcmToken(_i5.RxString? value) => super.noSuchMethod(
    Invocation.setter(#fcmToken, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingEnums(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingEnums, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(_i5.RxString? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingLogin(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingLogin, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingCheckIsApproved(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingCheckIsApproved, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentUser(_i5.Rxn<_i15.User>? value) => super.noSuchMethod(
    Invocation.setter(#currentUser, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentLoginUser(_i5.Rxn<_i16.LoginEntity>? value) => super.noSuchMethod(
    Invocation.setter(#currentLoginUser, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentUserIsApproved(_i5.Rxn<_i17.ApprovedEntity>? value) =>
      super.noSuchMethod(
        Invocation.setter(#currentUserIsApproved, value),
        returnValueForMissingStub: null,
      );

  @override
  set enumsResponse(_i5.Rxn<_i18.EnumsResponse>? value) => super.noSuchMethod(
    Invocation.setter(#enumsResponse, value),
    returnValueForMissingStub: null,
  );

  @override
  set alertTypes(_i5.RxList<_i18.EnumItem>? value) => super.noSuchMethod(
    Invocation.setter(#alertTypes, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedAlertIndex(_i5.RxInt? value) => super.noSuchMethod(
    Invocation.setter(#selectedAlertIndex, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_7<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i5.InternalFinalCallback<void>);

  @override
  _i5.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_7<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i5.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void changeAlertType(int? index) => super.noSuchMethod(
    Invocation.method(#changeAlertType, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void runAnimations() => super.noSuchMethod(
    Invocation.method(#runAnimations, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> registerUser({
    required String? name,
    required String? lastname,
    required String? phoneNumber,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [], {
              #name: name,
              #lastname: lastname,
              #phoneNumber: phoneNumber,
              #email: email,
              #password: password,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> quickLogout() =>
      (super.noSuchMethod(
            Invocation.method(#quickLogout, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> loginUser({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> checkUserIsApproved({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#checkUserIsApproved, [], {#userId: userId}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> registerWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#registerWithGoogle, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> loadUserFromPrefs() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserFromPrefs, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListener(_i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i13.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListenerId(Object? key, _i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeController extends _i1.Mock implements _i19.ThemeController {
  MockThemeController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Rx<_i6.ThemeMode> get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _FakeRx_6<_i6.ThemeMode>(
              this,
              Invocation.getter(#themeMode),
            ),
          )
          as _i5.Rx<_i6.ThemeMode>);

  @override
  _i5.RxBool get useSystemTheme =>
      (super.noSuchMethod(
            Invocation.getter(#useSystemTheme),
            returnValue: _FakeRxBool_4(
              this,
              Invocation.getter(#useSystemTheme),
            ),
          )
          as _i5.RxBool);

  @override
  set themeMode(_i5.Rx<_i6.ThemeMode>? value) => super.noSuchMethod(
    Invocation.setter(#themeMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set useSystemTheme(_i5.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#useSystemTheme, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_7<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i5.InternalFinalCallback<void>);

  @override
  _i5.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_7<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i5.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleTheme() => super.noSuchMethod(
    Invocation.method(#toggleTheme, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> setSystemTheme() =>
      (super.noSuchMethod(
            Invocation.method(#setSystemTheme, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setTheme(_i6.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setTheme, [mode]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool isLightMode() =>
      (super.noSuchMethod(
            Invocation.method(#isLightMode, []),
            returnValue: false,
          )
          as bool);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListener(_i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i13.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListenerId(Object? key, _i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
